
export const stateMap = [
  {
    messages: [],
    isBotTyping: false,
    headerText: 'User Testing 1.0',
    main: 'Narrator',
    fieldTop: 'Welcome to the Truth or Dare Turing Test!',
    fieldBottom: 'You are the first user testers. We love you and thank you for your help <3 ',
    input: 'DoubleButton',
    singleButtonText: '',
    button1Text: 'Truth',
    button2Text: 'Dare',
  },{
    messages: [],
    isBotTyping: false,
    headerText: 'User Testing 1.0',
    main: 'Chat',
    fieldTop: '',
    fieldBottom: '',
    input: 'MessageBar',
    singleButtonText: '',
    button1Text: '',
    button2Text: '',
  },{
    messages: [],
    isBotTyping: false,
    headerText: 'User Testing 1.0',
    main: 'Narrator',
    fieldTop: 'Time is up!',
    fieldBottom: 'Fear not and play again please =)',
    input: 'DoubleButton',
    singleButtonText: '',
    button1Text: 'Truth',
    button2Text: 'Dare',
  },{
    messages: [],
    isBotTyping: false,
    headerText: 'User Testing 1.0',
    main: 'AudioVis',
    fieldTop: '',
    fieldBottom: '',
    input: 'SingleButton',
    singleButtonText: 'Stop Recording',
    button1Text: '',
    button2Text: '',
  }
];