export const stateMap = [
  {
    step: 1, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'Ready to play some truth or dare?',
    fieldBottom: 'You are about to be paired with either a bot or a human. ',
    input: 'SingleButton',
    singleButtonText: 'Lets do it',
    button1Text: '',
    button2Text: '',
  },
  {
    step: 2, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'You will play three rounds of truth or dare. ',
    fieldBottom: 'The goal of the game is to correctly identify if you were talking to a human or to a bot. Before you start , you have 30 seconds to just chat with each other.',
    input: 'SingleButton',
    singleButtonText: 'Chat',
    button1Text: '',
    button2Text: '',
  },
  {
    step: 3, 
    timeLimit: 10,
    messages: [],
    headerText: '',
    main: 'Chat',
    fieldTop: '',
    fieldBottom: '',
    input: 'MessageBar',
    singleButtonText: '',
    button1Text: '',
    button2Text: '',
  }, 
  {
    step: 4, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'That is plenty of chatting! ',
    fieldBottom: 'Ready for round 1?',
    input: 'DoubleButton',
    singleButtonText: '',
    button1Text: 'Truth',
    button2Text: 'Dare',
  },
  {
    step: 5, 
    timeLimit: 10,
    messages: [],
    headerText: '',
    main: 'Chat',
    fieldTop: '',
    fieldBottom: '',
    input: 'MessageBar',
    singleButtonText: '',
    button1Text: '',
    button2Text: '',
  },
  {
    step: 6, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'Round 2',
    fieldBottom: '',
    input: 'DoubleButton',
    singleButtonText: '',
    button1Text: 'Truth',
    button2Text: 'Dare',
  },
  {
    step: 7, 
    timeLimit: 10,
    messages: [],
    headerText: '',
    main: 'Chat',
    fieldTop: '',
    fieldBottom: '',
    input: 'MessageBar',
    singleButtonText: '',
    button1Text: '',
    button2Text: '',
  }, {
    step: 8, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'Round 3',
    fieldBottom: '',
    input: 'DoubleButton',
    singleButtonText: '',
    button1Text: 'Truth',
    button2Text: 'Dare',
  },
  {
    step: 9, 
    timeLimit: 10,
    messages: [],
    headerText: '',
    main: 'Chat',
    fieldTop: '',
    fieldBottom: '',
    input: 'MessageBar',
    singleButtonText: '',
    button1Text: '',
    button2Text: '',
  }, 
  {
    step: 10, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'So what do you think?',
    fieldBottom: 'Was it a bot or a human?',
    input: 'DoubleButton',
    singleButtonText: '',
    button1Text: 'Bot',
    button2Text: 'Human',
  },
  {
    step: 11, 
    timeLimit: 1000,
    messages: [],
    headerText: '',
    main: 'Narrator',
    fieldTop: 'Correct!',
    fieldBottom: 'How did you know?',
    input: 'SingleButton',
    singleButtonText: 'Learn more',
    button1Text: '',
    button2Text: '',
  },
];